### ISSUE TITLE
Long modal is not scrollable and extends past window

### ISSUE THREAD

**Issue by brydonm** [DesignRevision/shards-ui#61]
Issue tracker is **ONLY** used for reporting bugs.

## Expected Behavior
If a modal extends past the window, I would expect it to scroll.

## Current Behavior
If a modal extends past the window, you cannot scroll down or see the content past the viewport.

## Possible Solution
In `_modal.scss`:
```css
   // Modal adjustments

   .modal {
     z-index: $zindex-modal;
+     max-height: 100vh;
+    overflow-x: scroll;
   }
```

Before: https://monosnap.com/direct/mInYN2o3UvH2Z0hWGVJOnm3IjZWDsj
After: https://api.monosnap.com/file/download?id=JjPewnilVwzts26Yt2rvhJOR0nQsrw

## Steps to Reproduce
1. Create a modal that is > 100vh

## Context (Environment)
I'm trying to build a form in a modal.
